---
- name: Install and configure Systemd Resolved
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not systemd_resolved_remove

- name: Stop and remove Systemd Resolved
  ansible.builtin.include_tasks:
    file: remove.yml
  when:
    - systemd_resolved_remove
